# Generated by Django 3.1 on 2020-08-18 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0005_word_reviewed'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='list',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='word',
            unique_together=set(),
        ),
    ]
